# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.predict_api import PredictApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestPredictApi(unittest.TestCase):
    """PredictApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.predict_api.PredictApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_predict_file_inference_service(self):
        """Test case for predict_file_inference_service

        """
        pass

    def test_predict_file_seldon_deployment(self):
        """Test case for predict_file_seldon_deployment

        """
        pass

    def test_predict_inference_service(self):
        """Test case for predict_inference_service

        """
        pass

    def test_predict_seldon_deployment(self):
        """Test case for predict_seldon_deployment

        """
        pass

    def test_read_predict_curl_inference_service(self):
        """Test case for read_predict_curl_inference_service

        """
        pass

    def test_read_predict_curl_seldon_deployment(self):
        """Test case for read_predict_curl_seldon_deployment

        """
        pass


if __name__ == '__main__':
    unittest.main()
