# coding: utf-8

"""
    Seldon-Deploy API.

    Documentation of Seldon-Deploy API.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_client
from seldon_deploy_client.api.git_api import GitApi  # noqa: E501
from seldon_deploy_client.rest import ApiException


class TestGitApi(unittest.TestCase):
    """GitApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_client.api.git_api.GitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_inference_service_git_restore(self):
        """Test case for inference_service_git_restore

        """
        pass

    def test_inference_service_git_revert(self):
        """Test case for inference_service_git_revert

        """
        pass

    def test_read_inference_service_git_diff(self):
        """Test case for read_inference_service_git_diff

        """
        pass

    def test_read_inference_service_git_logs(self):
        """Test case for read_inference_service_git_logs

        """
        pass

    def test_read_seldon_deployment_git_diff(self):
        """Test case for read_seldon_deployment_git_diff

        """
        pass

    def test_read_seldon_deployment_git_logs(self):
        """Test case for read_seldon_deployment_git_logs

        """
        pass

    def test_seldon_deployment_git_restore(self):
        """Test case for seldon_deployment_git_restore

        """
        pass

    def test_seldon_deployment_git_revert(self):
        """Test case for seldon_deployment_git_revert

        """
        pass


if __name__ == '__main__':
    unittest.main()
