# coding: utf-8

"""
    Seldon-Deploy API.

    Documentation of Seldon-Deploy API.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_client
from seldon_deploy_client.api.jobs_api import JobsApi  # noqa: E501
from seldon_deploy_client.rest import ApiException


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_client.api.jobs_api.JobsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_seldon_deployment_batch_job(self):
        """Test case for create_seldon_deployment_batch_job

        """
        pass

    def test_get_deployment_batch_job(self):
        """Test case for get_deployment_batch_job

        """
        pass

    def test_list_seldon_deployment_batch_jobs(self):
        """Test case for list_seldon_deployment_batch_jobs

        """
        pass


if __name__ == '__main__':
    unittest.main()
