# coding: utf-8

"""
    Seldon-Deploy API.

    Documentation of Seldon-Deploy API.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_client
from seldon_deploy_client.models.downward_api_volume_source import DownwardAPIVolumeSource  # noqa: E501
from seldon_deploy_client.rest import ApiException


class TestDownwardAPIVolumeSource(unittest.TestCase):
    """DownwardAPIVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDownwardAPIVolumeSource(self):
        """Test DownwardAPIVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = seldon_deploy_client.models.downward_api_volume_source.DownwardAPIVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
