# coding: utf-8

"""
    Seldon-Deploy API.

    Documentation of Seldon-Deploy API.  # noqa: E501

    OpenAPI spec version: v1alpha1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_client
from seldon_deploy_client.models.url import URL  # noqa: E501
from seldon_deploy_client.rest import ApiException


class TestURL(unittest.TestCase):
    """URL unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testURL(self):
        """Test URL"""
        # FIXME: construct object with mandatory attributes with example values
        # model = seldon_deploy_client.models.url.URL()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
