# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.drift_detector_api import DriftDetectorApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestDriftDetectorApi(unittest.TestCase):
    """DriftDetectorApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.drift_detector_api.DriftDetectorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_drift_detector_seldon_deployment(self):
        """Test case for create_drift_detector_seldon_deployment

        """
        pass

    def test_create_drift_detector_seldon_pipeline(self):
        """Test case for create_drift_detector_seldon_pipeline

        """
        pass

    def test_delete_drift_detector_seldon_deployment(self):
        """Test case for delete_drift_detector_seldon_deployment

        """
        pass

    def test_delete_drift_detector_seldon_pipeline(self):
        """Test case for delete_drift_detector_seldon_pipeline

        """
        pass

    def test_list_drift_detector_seldon_deployment(self):
        """Test case for list_drift_detector_seldon_deployment

        """
        pass

    def test_list_drift_detector_seldon_pipeline(self):
        """Test case for list_drift_detector_seldon_pipeline

        """
        pass

    def test_read_drift_detector_seldon_deployment(self):
        """Test case for read_drift_detector_seldon_deployment

        """
        pass

    def test_read_drift_detector_seldon_pipeline(self):
        """Test case for read_drift_detector_seldon_pipeline

        """
        pass


if __name__ == '__main__':
    unittest.main()
