# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.monitor_api import MonitorApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestMonitorApi(unittest.TestCase):
    """MonitorApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.monitor_api.MonitorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_seldon_deployment_feature_distributions(self):
        """Test case for seldon_deployment_feature_distributions

        """
        pass

    def test_seldon_deployment_feature_statistics(self):
        """Test case for seldon_deployment_feature_statistics

        """
        pass

    def test_seldon_pipeline_feature_distributions(self):
        """Test case for seldon_pipeline_feature_distributions

        """
        pass

    def test_seldon_pipeline_feature_statistics(self):
        """Test case for seldon_pipeline_feature_statistics

        """
        pass


if __name__ == '__main__':
    unittest.main()
