# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.kubernetes_resources_api import KubernetesResourcesApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestKubernetesResourcesApi(unittest.TestCase):
    """KubernetesResourcesApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.kubernetes_resources_api.KubernetesResourcesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_inference_service_resources(self):
        """Test case for list_inference_service_resources

        """
        pass

    def test_list_seldon_deployment_resources(self):
        """Test case for list_seldon_deployment_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
