# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.alerting_service_api import AlertingServiceApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestAlertingServiceApi(unittest.TestCase):
    """AlertingServiceApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.alerting_service_api.AlertingServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_alerting_service_list_alerts(self):
        """Test case for alerting_service_list_alerts

        List currently firing alerts.  # noqa: E501
        """
        pass

    def test_alerting_service_trigger_test_alert(self):
        """Test case for alerting_service_trigger_test_alert

        Triggers a test alert to check alerting workflow.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
