# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seldon_deploy_sdk
from seldon_deploy_sdk.api.environment_api import EnvironmentApi  # noqa: E501
from seldon_deploy_sdk.rest import ApiException


class TestEnvironmentApi(unittest.TestCase):
    """EnvironmentApi unit test stubs"""

    def setUp(self):
        self.api = seldon_deploy_sdk.api.environment_api.EnvironmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_cluster(self):
        """Test case for read_cluster

        """
        pass

    def test_read_health_check(self):
        """Test case for read_health_check

        """
        pass

    def test_read_user(self):
        """Test case for read_user

        """
        pass

    def test_read_version(self):
        """Test case for read_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
