from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from seldon_deploy_client.api.batch_jobs_api import BatchJobsApi
from seldon_deploy_client.api.drift_detector_api import DriftDetectorApi
from seldon_deploy_client.api.environment_api import EnvironmentApi
from seldon_deploy_client.api.explain_api import ExplainApi
from seldon_deploy_client.api.git_ops_api import GitOpsApi
from seldon_deploy_client.api.inference_services_api import InferenceServicesApi
from seldon_deploy_client.api.kubernetes_resources_api import KubernetesResourcesApi
from seldon_deploy_client.api.loadtest_jobs_api import LoadtestJobsApi
from seldon_deploy_client.api.metrics_server_api import MetricsServerApi
from seldon_deploy_client.api.outlier_detector_api import OutlierDetectorApi
from seldon_deploy_client.api.predict_api import PredictApi
from seldon_deploy_client.api.seldon_deployments_api import SeldonDeploymentsApi
