# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BatchJobPostResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'workflow_name': 'str',
        'workflow_uid': 'UID'
    }

    attribute_map = {
        'workflow_name': 'workflowName',
        'workflow_uid': 'workflowUID'
    }

    def __init__(self, workflow_name=None, workflow_uid=None):  # noqa: E501
        """BatchJobPostResponse - a model defined in Swagger"""  # noqa: E501

        self._workflow_name = None
        self._workflow_uid = None
        self.discriminator = None

        if workflow_name is not None:
            self.workflow_name = workflow_name
        if workflow_uid is not None:
            self.workflow_uid = workflow_uid

    @property
    def workflow_name(self):
        """Gets the workflow_name of this BatchJobPostResponse.  # noqa: E501

        Name of created Argo Workflow in: body  # noqa: E501

        :return: The workflow_name of this BatchJobPostResponse.  # noqa: E501
        :rtype: str
        """
        return self._workflow_name

    @workflow_name.setter
    def workflow_name(self, workflow_name):
        """Sets the workflow_name of this BatchJobPostResponse.

        Name of created Argo Workflow in: body  # noqa: E501

        :param workflow_name: The workflow_name of this BatchJobPostResponse.  # noqa: E501
        :type: str
        """

        self._workflow_name = workflow_name

    @property
    def workflow_uid(self):
        """Gets the workflow_uid of this BatchJobPostResponse.  # noqa: E501


        :return: The workflow_uid of this BatchJobPostResponse.  # noqa: E501
        :rtype: UID
        """
        return self._workflow_uid

    @workflow_uid.setter
    def workflow_uid(self, workflow_uid):
        """Sets the workflow_uid of this BatchJobPostResponse.


        :param workflow_uid: The workflow_uid of this BatchJobPostResponse.  # noqa: E501
        :type: UID
        """

        self._workflow_uid = workflow_uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchJobPostResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchJobPostResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
