# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContainerResourceMetricSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'container': 'str',
        'name': 'ResourceName',
        'target': 'MetricTarget'
    }

    attribute_map = {
        'container': 'container',
        'name': 'name',
        'target': 'target'
    }

    def __init__(self, container=None, name=None, target=None):  # noqa: E501
        """ContainerResourceMetricSource - a model defined in Swagger"""  # noqa: E501

        self._container = None
        self._name = None
        self._target = None
        self.discriminator = None

        if container is not None:
            self.container = container
        if name is not None:
            self.name = name
        if target is not None:
            self.target = target

    @property
    def container(self):
        """Gets the container of this ContainerResourceMetricSource.  # noqa: E501

        container is the name of the container in the pods of the scaling target  # noqa: E501

        :return: The container of this ContainerResourceMetricSource.  # noqa: E501
        :rtype: str
        """
        return self._container

    @container.setter
    def container(self, container):
        """Sets the container of this ContainerResourceMetricSource.

        container is the name of the container in the pods of the scaling target  # noqa: E501

        :param container: The container of this ContainerResourceMetricSource.  # noqa: E501
        :type: str
        """

        self._container = container

    @property
    def name(self):
        """Gets the name of this ContainerResourceMetricSource.  # noqa: E501


        :return: The name of this ContainerResourceMetricSource.  # noqa: E501
        :rtype: ResourceName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContainerResourceMetricSource.


        :param name: The name of this ContainerResourceMetricSource.  # noqa: E501
        :type: ResourceName
        """

        self._name = name

    @property
    def target(self):
        """Gets the target of this ContainerResourceMetricSource.  # noqa: E501


        :return: The target of this ContainerResourceMetricSource.  # noqa: E501
        :rtype: MetricTarget
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this ContainerResourceMetricSource.


        :param target: The target of this ContainerResourceMetricSource.  # noqa: E501
        :type: MetricTarget
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContainerResourceMetricSource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerResourceMetricSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
