# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Endpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'grpc_port': 'int',
        'http_port': 'int',
        'service_host': 'str',
        'service_port': 'int',
        'type': 'EndpointType'
    }

    attribute_map = {
        'grpc_port': 'grpcPort',
        'http_port': 'httpPort',
        'service_host': 'service_host',
        'service_port': 'service_port',
        'type': 'type'
    }

    def __init__(self, grpc_port=None, http_port=None, service_host=None, service_port=None, type=None):  # noqa: E501
        """Endpoint - a model defined in Swagger"""  # noqa: E501

        self._grpc_port = None
        self._http_port = None
        self._service_host = None
        self._service_port = None
        self._type = None
        self.discriminator = None

        if grpc_port is not None:
            self.grpc_port = grpc_port
        if http_port is not None:
            self.http_port = http_port
        if service_host is not None:
            self.service_host = service_host
        if service_port is not None:
            self.service_port = service_port
        if type is not None:
            self.type = type

    @property
    def grpc_port(self):
        """Gets the grpc_port of this Endpoint.  # noqa: E501


        :return: The grpc_port of this Endpoint.  # noqa: E501
        :rtype: int
        """
        return self._grpc_port

    @grpc_port.setter
    def grpc_port(self, grpc_port):
        """Sets the grpc_port of this Endpoint.


        :param grpc_port: The grpc_port of this Endpoint.  # noqa: E501
        :type: int
        """

        self._grpc_port = grpc_port

    @property
    def http_port(self):
        """Gets the http_port of this Endpoint.  # noqa: E501


        :return: The http_port of this Endpoint.  # noqa: E501
        :rtype: int
        """
        return self._http_port

    @http_port.setter
    def http_port(self, http_port):
        """Sets the http_port of this Endpoint.


        :param http_port: The http_port of this Endpoint.  # noqa: E501
        :type: int
        """

        self._http_port = http_port

    @property
    def service_host(self):
        """Gets the service_host of this Endpoint.  # noqa: E501


        :return: The service_host of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._service_host

    @service_host.setter
    def service_host(self, service_host):
        """Sets the service_host of this Endpoint.


        :param service_host: The service_host of this Endpoint.  # noqa: E501
        :type: str
        """

        self._service_host = service_host

    @property
    def service_port(self):
        """Gets the service_port of this Endpoint.  # noqa: E501


        :return: The service_port of this Endpoint.  # noqa: E501
        :rtype: int
        """
        return self._service_port

    @service_port.setter
    def service_port(self, service_port):
        """Sets the service_port of this Endpoint.


        :param service_port: The service_port of this Endpoint.  # noqa: E501
        :type: int
        """

        self._service_port = service_port

    @property
    def type(self):
        """Gets the type of this Endpoint.  # noqa: E501


        :return: The type of this Endpoint.  # noqa: E501
        :rtype: EndpointType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Endpoint.


        :param type: The type of this Endpoint.  # noqa: E501
        :type: EndpointType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Endpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Endpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
