# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class HealthCheckInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elastic': 'str',
        'prometheus': 'str'
    }

    attribute_map = {
        'elastic': 'Elastic',
        'prometheus': 'Prometheus'
    }

    def __init__(self, elastic=None, prometheus=None):  # noqa: E501
        """HealthCheckInfo - a model defined in Swagger"""  # noqa: E501

        self._elastic = None
        self._prometheus = None
        self.discriminator = None

        if elastic is not None:
            self.elastic = elastic
        if prometheus is not None:
            self.prometheus = prometheus

    @property
    def elastic(self):
        """Gets the elastic of this HealthCheckInfo.  # noqa: E501


        :return: The elastic of this HealthCheckInfo.  # noqa: E501
        :rtype: str
        """
        return self._elastic

    @elastic.setter
    def elastic(self, elastic):
        """Sets the elastic of this HealthCheckInfo.


        :param elastic: The elastic of this HealthCheckInfo.  # noqa: E501
        :type: str
        """

        self._elastic = elastic

    @property
    def prometheus(self):
        """Gets the prometheus of this HealthCheckInfo.  # noqa: E501


        :return: The prometheus of this HealthCheckInfo.  # noqa: E501
        :rtype: str
        """
        return self._prometheus

    @prometheus.setter
    def prometheus(self, prometheus):
        """Sets the prometheus of this HealthCheckInfo.


        :param prometheus: The prometheus of this HealthCheckInfo.  # noqa: E501
        :type: str
        """

        self._prometheus = prometheus

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HealthCheckInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HealthCheckInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
