# coding: utf-8

"""
    Seldon Deploy API

    API to interact and manage the lifecycle of your machine learning models deployed through Seldon Deploy.  # noqa: E501

    OpenAPI spec version: v1alpha1
    Contact: hello@seldon.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class V1FiringAlert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'severity': 'str',
        'description': 'str',
        'title': 'str',
        'active_at': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'severity': 'severity',
        'description': 'description',
        'title': 'title',
        'active_at': 'activeAt'
    }

    def __init__(self, name=None, severity=None, description=None, title=None, active_at=None):  # noqa: E501
        """V1FiringAlert - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._severity = None
        self._description = None
        self._title = None
        self._active_at = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if severity is not None:
            self.severity = severity
        if description is not None:
            self.description = description
        if title is not None:
            self.title = title
        if active_at is not None:
            self.active_at = active_at

    @property
    def name(self):
        """Gets the name of this V1FiringAlert.  # noqa: E501


        :return: The name of this V1FiringAlert.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1FiringAlert.


        :param name: The name of this V1FiringAlert.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def severity(self):
        """Gets the severity of this V1FiringAlert.  # noqa: E501


        :return: The severity of this V1FiringAlert.  # noqa: E501
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this V1FiringAlert.


        :param severity: The severity of this V1FiringAlert.  # noqa: E501
        :type: str
        """

        self._severity = severity

    @property
    def description(self):
        """Gets the description of this V1FiringAlert.  # noqa: E501


        :return: The description of this V1FiringAlert.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this V1FiringAlert.


        :param description: The description of this V1FiringAlert.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def title(self):
        """Gets the title of this V1FiringAlert.  # noqa: E501


        :return: The title of this V1FiringAlert.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this V1FiringAlert.


        :param title: The title of this V1FiringAlert.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def active_at(self):
        """Gets the active_at of this V1FiringAlert.  # noqa: E501


        :return: The active_at of this V1FiringAlert.  # noqa: E501
        :rtype: datetime
        """
        return self._active_at

    @active_at.setter
    def active_at(self, active_at):
        """Sets the active_at of this V1FiringAlert.


        :param active_at: The active_at of this V1FiringAlert.  # noqa: E501
        :type: datetime
        """

        self._active_at = active_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1FiringAlert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1FiringAlert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
